### ISSUE TITLE
Logo Proposal Scratchimage

### ISSUE THREAD

**Issue by Arslanshn** [cashwalk/ScratchImage#2]
Hi, I want to design a new logo for the project completely free...

**Comment by k-lpmg** [comment]
I would appreciate it if you contributed to the logo design work.

**Comment by Arslanshn** [comment]
https://drive.google.com/drive/folders/1MRwTGDDV4NvXLYJv2Ajv1ftfqaBfkchX?usp=sharing
hello I did a study I hope you like:)

**Comment by k-lpmg** [comment]
'scratchImage1.png' is really cool. Soon, I will incorporate it into the README.md. Thank you.
